name: Tests

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    # TODO: setting env in Github Secrets
    env:
      PUBLIC_BUCKET_SLUG: ${{ secrets.BUCKET_SLUG }}
      PUBLIC_BUCKET_READ_KEY: ${{ secrets.BUCKET_READ_KEY }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'pnpm'
      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test:unit
