name: Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    # TODO: setting env in Github Secrets
    env:
      BUCKET_SLUG: ${{ secrets.BUCKET_SLUG }}
      BUCKET_READ_KEY: ${{ secrets.BUCKET_READ_KEY }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necessary for deep history, especially for cache invalidation

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Adjust to your Node.js version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install Dependencies
        run: pnpm install

      - name: Run Tests
        run: pnpm test:unit
